sonar.projectKey=catch-oss_silverstripe-csp-logging
sonar.organization=catch-design


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=catch-oss_silverstripe-csp-logging
#sonar.projectVersion=1.0

# Source and test paths
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# PHP settings
sonar.php.coverage.reportPaths=coverage/php/coverage.xml
sonar.php.tests.reportPath=coverage/php/junit.xml

# Exclusions
sonar.exclusions=vendor/**,tests/**
